const router = require('express').Router()
const userRouter = require('./user')
const authRouter = require('./auth')
const tagRouter = require('./tag')
const coefficientRouter = require('./coefficient')
const languageRouter = require('./language')
const stopListRouter = require('./stopList')
const vacancyRouter = require('./vacancy')
const resumeRouter = require('./resume')
const articleRouter = require('./article')
const testimonialRouter = require('./testimonial')
const requestRegisterRouter = require('./requestRegister')

router.use('/users', userRouter)
router.use('/auth', authRouter)
router.use('/tags', tagRouter)
router.use('/coefficients', coefficientRouter)
router.use('/languages', languageRouter)
router.use('/stopList', stopListRouter)
router.use('/vacancies', vacancyRouter)
router.use('/resume', resumeRouter)
router.use('/articles', articleRouter)
router.use('/testimonials', testimonialRouter)
router.use('/requestRegister', requestRegisterRouter)

module.exports = router